#   WProtectWorlds[世界保护]
#  作者: Wshape1
#  作者新手，做得不好请见谅
# 本插件开源，禁止倒卖
#使用/wpw查看帮助

# 发送提示模式:
#  0=聊天框发送 
#  1=底部Tip发送
#  2=底部Popuop发送
SendType: 0

# 玩家破坏/放置方块提示语
Message: "§c本世界已被保护"

# 一段句子的头号
Prefix: "§c[§6W世界保护§c]"

#添加一个命令管理员
#可使用本插件所有命令权限
#命令: 添加/wpw cadd <名字>   删除/wpw cdel <名字>
# CONSOLE不能删除,否则后台将不能执行命令
# 这可能是个bug
CmdAdmins:
- "CONSOLE"

#添加世界管理员
# 允许在被保护世界破坏/放置方块
Admins:

# 被保护的世界
Worlds: